[package]
name = "ag_parsing"
version = "0.1.0"
authors = ["Aurelien Foucault <aurelien.foucault@epitech.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"